version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - ${PGPORT}:5432
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
