version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - ${PGPORT}:5432
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    env_file:
      - .env.dev
    restart:
      always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "80:8000"

    entrypoint: [ "sh", "docker-entrypoint.sh" ]
