# Generated by Django 4.2.5 on 2023-10-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
    ]
